#!/usr/bin/env node
/**
 * Navbar Template Module
 * Provides a consistent navbar script tag for all pages
 * 
 * This is a comprehensive JavaScript translation of navbar_template.py with full feature parity.
 */

/**
 * Generate navbar script tag with appropriate relative paths
 * 
 * Python equivalent: get_navbar_html(level)
 * 
 * @param {string} level - The directory level - "root", "directory", or "subdirectory"
 *                        - "root": for index.html (at repository root)
 *                        - "directory": for files in index.directory/
 *                        - "subdirectory": for files in index.directory/trades/ etc.
 * 
 * @returns {string} Comment indicating navbar is generated by navbar.js
 * 
 * @example
 * const navbarHtml = getNavbarHtml("root");
 * const navbarHtml = getNavbarHtml("subdirectory");
 */
function getNavbarHtml(level = 'root') {
    // The navbar is now generated dynamically by navbar.js
    // No need to generate HTML, just return a comment
    return '  <!-- Navigation - Generated by navbar.js -->';
}

// Export the function for use in other modules
module.exports = {
    getNavbarHtml
};
